# Generated by Django 3.0.5 on 2020-04-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.TextField(help_text='Name')),
                ('usn', models.TextField(help_text='USN', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email (Use CMRIT Email)', max_length=254)),
                ('phone', models.TextField(help_text='Phone')),
            ],
        ),
    ]
