# Generated by Django 3.0.5 on 2020-04-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
        migrations.AddField(
            model_name='register',
            name='score1',
            field=models.TextField(default=0, help_text='Test 1 Score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='score2',
            field=models.TextField(default=0, help_text='Test 2 Score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='score3',
            field=models.TextField(default=0, help_text='Test 3 Score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='score4',
            field=models.TextField(default=0, help_text='Test 4 Score'),
            preserve_default=False,
        ),
    ]
