# Generated by Django 3.0.5 on 2020-04-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200409_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_time', models.TextField(help_text='Enter the duration of the test')),
                ('num_questions', models.TextField(help_text='Number of questions in the test')),
                ('test_number', models.TextField(help_text='Test Number')),
                ('test_name', models.TextField(help_text='Test Name')),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='score5',
            field=models.TextField(default=0, help_text='Test 5 Score'),
            preserve_default=False,
        ),
    ]
