# Generated by Django 3.0.5 on 2020-04-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200411_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructions',
            name='num_questions',
            field=models.CharField(help_text='Number of questions in the test', max_length=5),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='test_name',
            field=models.CharField(help_text='Test Name', max_length=25),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='test_number',
            field=models.CharField(help_text='Test Number', max_length=5),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='test_time',
            field=models.CharField(help_text='Enter the duration of the test', max_length=5),
        ),
    ]
