# Generated by Django 3.0.5 on 2020-04-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200411_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(help_text='Email (Use CMRIT Email)', max_length=25),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(help_text='Name', max_length=25),
        ),
        migrations.AlterField(
            model_name='register',
            name='score1',
            field=models.CharField(help_text='Test 1 Score', max_length=5),
        ),
        migrations.AlterField(
            model_name='register',
            name='score2',
            field=models.CharField(help_text='Test 2 Score', max_length=5),
        ),
        migrations.AlterField(
            model_name='register',
            name='score3',
            field=models.CharField(help_text='Test 3 Score', max_length=5),
        ),
        migrations.AlterField(
            model_name='register',
            name='score4',
            field=models.CharField(help_text='Test 4 Score', max_length=5),
        ),
        migrations.AlterField(
            model_name='register',
            name='score5',
            field=models.CharField(help_text='Test 5 Score', max_length=5),
        ),
        migrations.AlterField(
            model_name='register',
            name='usn',
            field=models.CharField(help_text='USN', max_length=10, primary_key=True, serialize=False),
        ),
    ]
