# Generated by Django 3.0.5 on 2020-04-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200413_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(help_text='Email (Use CMRIT Email)', max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='usn',
            field=models.CharField(help_text='USN', max_length=10),
        ),
    ]
